### ISSUE TITLE
Publishing ROS along with streaming on UDP port

### ISSUE THREAD

**Issue by joshi-bharat** [clydemcqueen/gscam2#10]
@clydemcqueen I am trying to run ROS on BlueROV (publish camera topic) and pass video stream to UDP (similar to original BlueROV). The idea is to interrupt BlueROV manually if it does something crazy. We are trying to run some computer vision algorithms for object detection.

Do you think this is even possible? Do you have any ideas about that? 

Thanks for the great repo. I will be following your work.

**Comment by clydemcqueen** [comment]
Re: turning BlueROV video stream into ROS images

Have you seen https://github.com/patrickelectric/bluerov_ros_playground? There's a script to capture video using gstreamer and publish images on ros1: https://github.com/patrickelectric/bluerov_ros_playground/blob/master/src/bluerov/video.py

You can also use gscam2 to do this on ros2.

Re: CV algorithms to do object detection

I have not tried this, but a quick search brings up a number of papers talking about "underwater object detection."

I hope this helps.

**Comment by joshi-bharat** [comment]
@clydemcqueen thanks. I will try these.
