### ISSUE TITLE
h264 encoded stream through gscam

### ISSUE THREAD

**Issue by sapoluri** [clydemcqueen/gscam2#15]
My current stream is 4k @ 60 fps and I intend to stream it over a network to a remote host. Consequently, I want to encode the stream to h264 before streaming it.

I was planning to do something like:
export gscam_config="camsrc name=cam ...... ! vaapih264enc"

However, the sink for gscam expects RGB format so the above command won't work. Neither will a videoconvert at the end because it is encoded data.

Is it possible to somehow allow the encoded data to masquerade as RGB data to be obtained from /image_raw topic and then I can decide how to decode it back to individual frames?

**Comment by sapoluri** [comment]
I think what I am asking is not possible through gscam. My idea is to modify gscam and provide topic type as a param so I can set it to sensors_msgs/image or video/encoded and then after modification I hope gscam will help me publish an encoded video stream. The reason I am not looking at other ROS nodes that actually take /image_raw as input and give video/encoded as output is performance. I use HW accelerated encoding and I use dma buffer sharing between the gstreamer plugins used for streaming and encoding.

**Comment by clydemcqueen** [comment]
Why not use gst-launch-1.0 to run the entire pipeline? E.g., 
camsrc name=cam ...... ! vaapih264enc ! h264parse ! rtph264pay config-interval=10 ! udpsink ......

It might be possible to grab h264 buffers after encoding and write them to a ROS message. The key benefit in my mind is to use rosbag to record and play back compressed images. It may be worth doing a bit of research on this.
