### ISSUE TITLE
GSCAM2 with YUV output

### ISSUE THREAD

**Issue by suyash-narain** [clydemcqueen/gscam2#30]
I am using a USB camera with YUV image format with GSCAM2. Gscam_main ros2 node converts the image format to rgb8 and publishes gstreamer output to /image_raw topic which can then be visualized on ros2 image_view package. 

I was trying to remove the RGB8 conversion in the code by replacing all the instances of `sensor_msgs::image_encodings::RGB8 ` in gscam_node.cpp to `sensor_msgs::image_encodings::yuv422` as this is the only yuv format found in sensor_images::image_encodings. 
After which I replaced the following line in https://github.com/clydemcqueen/gscam2/blob/8fd7dc739e28acfc1b2b9cc9ed53efde5bb214a8/src/gscam_node.cpp#L146 

from 
```  
if (cxt_.image_encoding_ == sensor_msgs::image_encodings::RGB8) {
    caps = gst_caps_new_simple(
      "video/x-raw",
      "format", G_TYPE_STRING, "RGB",
      nullptr);
```
to 
```  
if (cxt_.image_encoding_ == sensor_msgs::image_encodings::YUV422) {
    caps = gst_caps_new_simple(
      "video/x-raw",
      "format", G_TYPE_STRING, "YUY2",
      nullptr);
```
I am providing 'YUY2' format in the pipeline because this is the default output format as found using gst-launch-1.0 for my pipeline

`gst-launch-1.0 -v v4l2src device=/dev/video2 ! video/x-raw,width=640. height=480, framerate=30/1 ! videoconvert`

But I am getting really weird outputs as below:
![image_yuv](https://user-images.githubusercontent.com/78979784/184429761-6dd5e7b6-a9f5-4b7a-9093-270972e55efc.jpeg)

How can I keep the default camera format unchanged for output? I want the node to give output in YUV/YUY2 format itself, same as default camera input. In ROS2 humble, RVIZ can visualize YUV images directly without the need for converting it to RGB, and I'd like gscam2 output to be in YUV. 

thanks

**Comment by clydemcqueen** [comment]
I have a USB camera that claims to support `'YUYV' (YUYV 4:2:2)` and I was able to get it to display correctly in rviz2 using `sensor_msgs::image_encodings::YUV422_YUY2`. Perhaps this will help? I'll submit a PR to add support for this.

**Comment by clydemcqueen** [comment]
See https://github.com/clydemcqueen/gscam2/pull/31

**Comment by suyash-narain** [comment]
thank you. Following https://github.com/clydemcqueen/gscam2/pull/31 worked for me. I will close the issue
