### ISSUE TITLE
gstreamer search paths for custom elements

### ISSUE THREAD

**Issue by BrettRD** [clydemcqueen/gscam2#33]
I'd like to use this package with `aravissrc` for genicam industrial cameras

aravis installs `libgstaravis.0.8.so` to `/usr/local/lib/x86_64-linux-gnu/`
and I can load it with 
`gst-launch-1.0 --gst-plugin-path="/usr/local/lib/x86_64-linux-gnu" aravissrc camera-name="Aravis-Fake-GV01" ! videoconvert ! ximagesink`

How do I pass a gst-plugin-path to gscam2?
I'd like to avoid relying on environment variables

**Comment by clydemcqueen** [comment]
Good feature request.

To make this generally useful, I think it makes sense to add a `gst_plugin_path` parameter, and then call `gst_registry_scan_path` to add the plugins to the registry before parsing the config. I just did some experiments and this seems to work.

Thoughts?

**Comment by BrettRD** [comment]
#34 works great
