### ISSUE TITLE
camera.ini parameters

### ISSUE THREAD

**Issue by zoldaten** [clydemcqueen/gscam2#39]
hi!
i see default camera.ini in ros2_ws/src/gscam2/cfg/my_camera.ini  and want to implement my camera ones.
i got them after Kalibr calibration. but i do not have rectification and projection matrixs.
i use mono camera.
my camera matrix looks like:
camera matrix
351.774060 0.000000 290.713492
0.000000 468.945113 235.782768
0.000000 0.000000 1.000000

may be if i set them to zeros it will be OK ?

rectification
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0

projection
0.0 0.000000 0.0 0.000000
0.000000 0.0 0.0 0.000000
0.000000 0.000000 0.000000 0.000000

**Comment by clydemcqueen** [comment]
You may have better luck copying rectification and projection matrices from this example: https://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

**Comment by zoldaten** [comment]
got it! thanks!

```
rectification
1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000

projection
1.000000 0.000000 0.000000 0.000000
0.000000 1.000000 0.000000 0.000000
0.000000 0.000000 1.000000 0.000000
```
