### ISSUE TITLE
rclcpp_components/register_node_macro.hpp: No such file or directory (Unable to build package)

### ISSUE THREAD

**Issue by Sail-Lab** [clydemcqueen/gscam2#7]
When I follow the instructions and run 'colcon build' I receive this error:

/home/USER/ros2/gscam2_ws/src/gscam2/src/subscriber_node.cpp:37:10: fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory
 #include "rclcpp_components/register_node_macro.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/subscriber_node.dir/src/subscriber_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/subscriber_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
//opt/ros/eloquent/lib/libimage_transport.so: undefined reference to `message_filters::Connection::Connection(std::function<void ()> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [gscam_main] Error 1
make[1]: *** [CMakeFiles/gscam_main.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< gscam [0.63s, exited with code 2]
`

**Comment by clydemcqueen** [comment]
Is `ros-eloquent-rclcpp-components` installed?

At the moment gscam2 depends on ROS2 Eloquent. If there's interest, I could release this for Dashing, Eloquent and Foxy.

**Comment by Sail-Lab** [comment]
Yes those releases would be quite useful!

**Comment by Sail-Lab** [comment]
Yes those releases would be quite useful!

> Is `ros-eloquent-rclcpp-components` installed?
> 
> At the moment gscam2 depends on ROS2 Eloquent. If there's interest, I could release this for Dashing, Eloquent and Foxy.

**Comment by Sail-Lab** [comment]
ros-eloquent-rclcpp-components is already installed. Why is not recognizing that for proper build?

> Is `ros-eloquent-rclcpp-components` installed?
> 
> At the moment gscam2 depends on ROS2 Eloquent. If there's interest, I could release this for Dashing, Eloquent and Foxy.

**Comment by clydemcqueen** [comment]
I added a Dockerfile that builds & runs for me, this mail help in debugging. https://github.com/clydemcqueen/gscam2/blob/master/Dockerfile

**Comment by pvmilk** [comment]
@clydemcqueen I have similar issue in ros2-foxy. 
You need to add "rclcpp_components" in two locations in CMakeLists.txt


[rclcpp_components.txt](https://github.com/clydemcqueen/gscam2/files/6604101/rclcpp_components.txt)
