### ISSUE TITLE
gstreamer assertion in gst_buffer_resize_range

### ISSUE THREAD

**Issue by hannes09** [clydemcqueen/gscam2#9]
I am getting the following assertion, when running the example pipeline:
`gst_buffer_resize_range: assertion 'gst_buffer_is_writable (buffer)' failed`

The pipeline:
`export GSCAM_CONFIG='videotestsrc pattern=snow ! video/x-raw,width=1280,height=720 ! videoconvert'`

cmd:
`ros2 run gscam gscam_main`

My system:
Ubuntu 20.04 64Bit
gstreamer 1.16.2
ROS 2 Foxy Fitzroy

Also tested gscam from ROS, but got the same assertion.

**Comment by clydemcqueen** [comment]
Thanks for the bug report. I isolated this and will provide a patch.
